name: build-test-push

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --pull -t nickstamat/curl-jq:7.81.0-1.6 -t nickstamat/curl-jq:latest .

      - name: Download container-structure-test
        run: |
          set -e
          curl --retry 5 -fSLo container-structure-test https://storage.googleapis.com/container-structure-test/v1.11.0/container-structure-test-linux-amd64
          echo '1524da5fd5a0fc88c4c9257a3de05a45f135df07e6a684380dd5f659b9ce189b *container-structure-test' | sha256sum -c -
          chmod +x ./container-structure-test

      - name: Test image
        run: ./container-structure-test test --image nickstamat/curl-jq:latest --config structure-test.yaml

      - name: Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push --all-tags nickstamat/curl-jq
